name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and test
        run: mvn -B verify

      - name: Generate Javadoc
        run: mvn javadoc:javadoc

      - name: Copy Javadoc to temp folder
        run: |
          mkdir -p temp-docs
          cp -R target/site/apidocs/* temp-docs/

      - name: Create redirect index.html
        run: |
          echo '<!DOCTYPE html>
          <html lang="en">
            <head>
              <meta http-equiv="refresh" content="0; url=overview-summary.html">
              <title>Redirecting…</title>
            </head>
            <body>
              <p>If you are not redirected automatically, follow this <a href="overview-summary.html">link</a>.</p>
            </body>
          </html>' > temp-docs/index.html
          touch temp-docs/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./temp-docs
          publish_branch: gh-pages
          force_orphan: true
